# # Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
# version: 2.1
# # Use a package of configuration called an orb.
# jobs:
#   build: 
#     docker:
#       - image: circleci/node:4.8.2
#     steps:
#       - checkout
#       - run: echo "description - You are doing the CircleCI Training Koans. Make sure to read the offical docs at circleci.com/docs" 
#       - run : echo "Hello world"

version: 2
jobs:
  build:
    docker: 
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: "'run' statements can actually contain a 'name' and 'command' argument as well"
          command: | 
            echo "You can even have multiline commands."
      - restore_cache: 
          key: v1-dependencies-
      - run: mkdir ~/cache/
      - run: echo "testfile" > ~/cache/log.txt
      - save_cache:
          key: v1-dependencies-
          paths: ~/cache

